name: Checkout Demo

on:
  workflow_dispatch

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List Files
        run: ls