name: My First Workflow

on:
  workflow_dispatch


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: python --version
      - run: node --version
      - run: git --version

# jobs:
#   hello:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Say Hello
#         run: echo "Hello Lalit!"

#       - name: Print Date
#         run: date

#       - name: Print Current Folder
#         run: pwd

#       - name: Show Files
#         run: ls